"""Evidence contract definitions for Ojo de Dios."""

from dataclasses import dataclass, field
from typing import Any

from app.core.errors import ContractError

EVIDENCE_QUALITY_NONE = "none"
EVIDENCE_QUALITY_LOW = "low"
EVIDENCE_QUALITY_MEDIUM = "medium"
EVIDENCE_QUALITY_HIGH = "high"
EVIDENCE_QUALITY_CRITICAL = "critical"

VALID_EVIDENCE_QUALITIES = {
    EVIDENCE_QUALITY_NONE,
    EVIDENCE_QUALITY_LOW,
    EVIDENCE_QUALITY_MEDIUM,
    EVIDENCE_QUALITY_HIGH,
    EVIDENCE_QUALITY_CRITICAL,
}

RESULT_SUCCESS = "SUCCESS"
RESULT_FAILED = "FAILED"
RESULT_PARTIAL = "PARTIAL"
RESULT_SKIPPED = "SKIPPED"
RESULT_MANUAL_REQUIRED = "MANUAL_REQUIRED"
RESULT_MISSING_TOOL = "MISSING_TOOL"

VALID_RESULT_STATUSES = {
    RESULT_SUCCESS,
    RESULT_FAILED,
    RESULT_PARTIAL,
    RESULT_SKIPPED,
    RESULT_MANUAL_REQUIRED,
    RESULT_MISSING_TOOL,
}


@dataclass
class EvidenceRecord:
    """Evidence generated by a technique run."""

    evidence_id: str
    run_id: str
    target_id: str
    technique_id: str
    module_id: str
    evidence_type: str
    quality: str
    summary: str
    content: dict[str, Any] = field(default_factory=dict)
    source: str = "system"
    demo: bool = False
    real_execution: bool = True
    created_at: str | None = None


def validate_evidence_record(record: EvidenceRecord) -> None:
    """Validate an evidence record contract."""
    if not record.evidence_id:
        raise ContractError("Evidence id cannot be empty.")
    if not record.run_id:
        raise ContractError("Run id cannot be empty.")
    if not record.target_id:
        raise ContractError("Target id cannot be empty.")
    if not record.technique_id:
        raise ContractError("Technique id cannot be empty.")
    if not record.module_id:
        raise ContractError("Module id cannot be empty.")
    if record.quality not in VALID_EVIDENCE_QUALITIES:
        raise ContractError("Invalid evidence quality.")
    if record.demo and record.real_execution:
        raise ContractError("Demo evidence cannot be marked as real execution.")
