"""Base constants for Ojo de Dios."""

PRODUCT_INTERNAL_NAME_DEFAULT = "ojo_de_dios"
PRODUCT_DISPLAY_NAME_DEFAULT = "Ojo de Dios"
APP_VERSION_DEFAULT = "0.1.0"

EXECUTION_MODE_DEMO = "demo"
EXECUTION_MODE_DRY_RUN = "dry_run"
EXECUTION_MODE_CONTROLLED = "controlled"
EXECUTION_MODE_EXPERT = "expert"

DEFAULT_EXECUTION_MODE = EXECUTION_MODE_DEMO

VALID_EXECUTION_MODES = {
    EXECUTION_MODE_DEMO,
    EXECUTION_MODE_DRY_RUN,
    EXECUTION_MODE_CONTROLLED,
    EXECUTION_MODE_EXPERT,
}

HEALTH_STATUS_OK = "ok"
